version: "3.8"
services:
  books_db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "bookdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"